/*
 * Generated by apps/web/plugins/pwa.ts — do not edit, and do not check in.
 * Every decision this file makes is explained there.
 */
'use strict';

const VERSION = "db499ebfc2ae";
const BASE = "/";
const ASSETS = "/assets/";
const SHELL = [
  "/",
  "/assets/index-COMWV1JW.js",
  "/assets/index-DIw8wOm-.css",
  "/manifest.webmanifest",
  "/icons/icon-192.png",
  "/icons/icon-512.png",
  "/icons/icon-maskable-512.png"
];
const FONT_ORIGINS = ["https://fonts.googleapis.com","https://fonts.gstatic.com"];

/* Versioned, so activating a new worker cannot read a byte written by the old one. */
const PRECACHE = 'txt2sfx-shell-' + VERSION;
const RUNTIME = 'txt2sfx-lazy-' + VERSION;
/* Not versioned: a webfont is somebody else's immutable, content-addressed file and has
   nothing to do with which build of this application is installed. */
const FONTS = 'txt2sfx-fonts';

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches.open(PRECACHE).then((cache) =>
      /* 'reload' bypasses the HTTP cache for the install fetch. Without it, a worker
         installing minutes after a deploy can precache the *previous* index.html — the
         document is served with a short max-age, and a shell whose HTML and hashed
         assets come from two different builds is a blank page nobody can explain. */
      cache.addAll(SHELL.map((url) => new Request(url, { cache: 'reload' }))),
    ),
  );
  /* Nothing is taken over here, on purpose. The tab holds unsaved recipes, a decoded
     reference and possibly a running search, so the message handler below is the only
     place this worker ever stops waiting — and the page decides when that is. */
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    (async () => {
      const names = await caches.keys();
      await Promise.all(
        names
          .filter((name) => name !== PRECACHE && name !== RUNTIME && name !== FONTS)
          .map((name) => caches.delete(name)),
      );
      /* Take over tabs that were opened before any worker existed, so the first visit is
         also the one that becomes usable offline. Safe here and not on install: by this
         point the shell is fully precached. */
      await self.clients.claim();
    })(),
  );
});

/* The other half of the update prompt in lib/updates.ts: the page decides when. */
self.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'skip-waiting') self.skipWaiting();
});

/* 'Vary: Accept-Encoding' is on everything a static host serves, and the Cache API honours
   it by comparing the stored request's headers with the new one's. A shell precached by a
   plain fetch would then miss when the same file is asked for as a script or a stylesheet,
   and the symptom is an application that is mysteriously online-only. The URL is the whole
   identity of a content-hashed file, so there is nothing here for Vary to be right about. */
const MATCH = { ignoreVary: true };

/** Serve from a cache, falling back to the network and remembering what it answered. */
async function cacheFirst(request, cacheName) {
  const cache = await caches.open(cacheName);
  const hit = await cache.match(request, MATCH);
  if (hit !== undefined) return hit;
  const response = await fetch(request);
  /* Only a real 200. Caching a 404 or a captive portal's redirect would pin the failure
     for as long as the cache lives, which is exactly as long as nobody can explain it. */
  if (response.ok && response.status === 200) await cache.put(request, response.clone());
  return response;
}

self.addEventListener('fetch', (event) => {
  const request = event.request;
  if (request.method !== 'GET') return;
  const url = new URL(request.url);

  /* The base address itself, not every navigation. This application has no routes — the
     screens are React state — so the only document it owns is that one, and answering
     more broadly would hand the shell to somebody who navigated to /chat.txt or /og.png
     on purpose. Query and fragment are not part of the comparison, which is what lets an
     OAuth return and a shared-recipe link open offline like any other visit. */
  if (request.mode === 'navigate' && url.pathname === BASE) {
    event.respondWith(
      (async () => {
        const cached = await caches.match(BASE, { cacheName: PRECACHE, ignoreVary: true });
        /* The network is the fallback rather than the other way round: an installed
           application that shows a browser error page because a phone is in a lift is
           the failure this whole file exists to prevent. */
        return cached !== undefined ? cached : fetch(request);
      })(),
    );
    return;
  }

  if (url.origin === self.location.origin) {
    if (SHELL.indexOf(url.pathname) !== -1) {
      event.respondWith(cacheFirst(request, PRECACHE));
    } else if (url.pathname.startsWith(ASSETS)) {
      /* A lazy chunk — an audio encoder, most likely. Cached when it is first reached
         rather than at install time, so nobody downloads a megabyte for a format they
         never export. */
      event.respondWith(cacheFirst(request, RUNTIME));
    }
    return;
  }

  if (FONT_ORIGINS.indexOf(url.origin) !== -1) {
    event.respondWith(
      /* Re-issued as a CORS request. The stylesheet link is 'no-cors', whose response is
         opaque — status 0, body unreadable — and storing one would mean caching an error
         indistinguishable from a success. Both Google Fonts origins answer CORS requests
         with 'Access-Control-Allow-Origin: *', so asking properly gives a response this
         worker can actually check before it keeps it. */
      cacheFirst(new Request(url.href, { mode: 'cors', credentials: 'omit' }), FONTS).catch(
        /* Offline with nothing cached. The stacks in styles.css fall back to system
           faces, so failing here is a different typeface and not a broken page. */
        () => fetch(request),
      ),
    );
  }

  /* Everything else — the bank, Freesound, the model vendors, chat.txt, og.png — is not
     answered here at all, which leaves it to the network exactly as if no worker existed. */
});
